Sosna/geolocation
schizofrenicy/EcoDrive pull request #11
Opened 2023-12-06 21:51 UTC by Sosssen

2023-12-06 23:47 UTC, H3w9VH3F4L4Tq5MbsfRi requested changes
FICZUR RIKŁEST: te CELNE printy o dostępnie do lokalizacji proszę przerobić na snackbar

2023-12-06 23:47 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/register_ride_screen.dart
> +    }
tego IFa można wnieść do tego wyżej (linie 31-38)

2023-12-06 23:47 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/register_ride_screen.dart
> +      if (distance > 5.0) {
5.0 jako magic number
można wynieść do Const'a

2023-12-06 23:47 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/classes/ride.dart
> +  List<Position> positionList = [];
jeżeli zostanie taka architektura jak jest teraz (czyli explicite serializacja obiektów Position), to musisz dodać uzupełnianie tego pola przy GetAll() z bazy

2023-12-07 22:05 UTC, Sosssen commented on lib/classes/ride.dart
> +  List<String> positionJsonList = [];
nie ma jusz

2023-12-07 22:12 UTC, Sosssen commented on lib/register_ride_screen.dart
> +    if (!serviceEnabled) {
<img width="355" alt="image" src="https://github.com/schizofrenicy/EcoDrive/assets/72930007/1d39e448-29ea-460c-8666-90dcff4acaee">

2023-12-07 22:16 UTC, Sosssen commented on lib/classes/ride.dart
> +  List<Position> positionList = [];
zmieniona architektura

2023-12-07 22:43 UTC, H3w9VH3F4L4Tq5MbsfRi approved these changes
gut

2023-12-07 22:43 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/register_ride_screen.dart
> +    if (!serviceEnabled) {
norbecik się chuja zna
resolved

2023-12-07 22:43 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/register_ride_screen.dart
> +    }
wykłóciłeś się, niech ci będzie

2023-12-07 22:46 UTC, merged