Saj/metrics intro
schizofrenicy/EcoDrive pull request #12
Opened 2023-12-07 01:06 UTC by H3w9VH3F4L4Tq5MbsfRi

2023-12-08 19:22 UTC, Sosssen requested changes
GENERALNIE fajne, no ale trochę do zmiany

2023-12-08 19:22 UTC, Sosssen commented on lib/singletons/metric.dart
> +      double acc = speed / MetricConstants.KMHtoMS / time.inSeconds;
dobra skumałem ocb xddd daj nawias przy pierwszym dzieleniu dla czytelności

2023-12-08 19:22 UTC, Sosssen commented on lib/singletons/metric.dart
> +      if (currDifference > minDifference) {
`>=`? po co przypisywać jak równe

2023-12-08 19:22 UTC, Sosssen commented on lib/singletons/metric.dart
> +  static int _FindClosestGpsSample(Ride ride, DateTime sample, int lastGpsIndex) {
oj no nie wiem, tak jak pisałem wcześniej, po piździe dla mnie ten ostatni parametr
tera trochę niby zaoszczędzasz na złożoności, ale IMO wypierdol, zrób proste a na pewno bez błędu (bo ja coś czuję że tu może być corner case) i załóż issue, bo to da się zrobić w logn - szybciej niż ty teraz zrobiłeś

2023-12-08 19:22 UTC, Sosssen commented on lib/singletons/metric.dart
> +        overrunEndIdx = i - 1;
EDGE CASE
jak overrun trwa do ostatniego punktu, to nigdy ten overrun się nie zakończy w twojej logice (nie zapiszesz go)

2023-12-08 19:22 UTC, Sosssen commented on lib/singletons/metric.dart
> +            MetricConstants.minOverrunDuration) {
DOBRA KURWA TAKIE SAME UWAGI JAK DO FUNKCJI WCZEŚNIEJ
nie czytałem logiki tego jeszcze, przeczytam w drugiej rundzie, bo mnie pokonały zagnieżdżenia (pierwsza funkcja i tak do refactoru, bo nie działa, jest kom)

2023-12-08 19:30 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/classes/overrun.dart
> +enum OverrunType { Undefined, TooHighRPM, TooFastAcceleration }
done

2023-12-08 19:32 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/classes/overrun.dart
> +  late int GPSstartIdx;
done

2023-12-08 19:33 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/classes/overrun.dart
> +  late int GPSendIdx;
done

2023-12-08 19:43 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/classes/overrun.dart
> +  Overrun.make(this.GPSstartIdx, this.GPSendIdx, this.type);
done

2023-12-08 19:44 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/classes/overrun.dart
> +  Overrun();
done

2023-12-08 19:46 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/screens/home_screen.dart
> +                var rides = await Db.getAll();
done

2023-12-08 19:46 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/screens/home_screen.dart
> +                  print('Obliczono przekroczenia dla przejazdu nr ${ride.id}:');
done

2023-12-08 19:46 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/screens/home_screen.dart
> +                print("Przeliczone wszystkie przejazdy");
unchanged

2023-12-08 19:48 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/screens/home_screen.dart
> +                // TEMP
done

2023-12-08 19:50 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/screens/register_ride_screen.dart
> +    MetricCalculator.CalcMetrics(ride);
#17

2023-12-08 19:53 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metric.dart
> +class MetricConstants {
done

2023-12-08 19:56 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metric.dart
> +  static List<Overrun> _TooHighRPM(Ride r) {
done

2023-12-08 19:57 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metric.dart
> +  static List<Overrun> _TooFastAcceleration(Ride r) {
done

2023-12-08 20:00 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metric.dart
> +  static List<Overrun> _TooHighRPM(Ride r) {
done

2023-12-08 20:00 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metric.dart
> +  static List<Overrun> _TooFastAcceleration(Ride r) {
done

2023-12-08 20:01 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metric.dart
> +  static List<double> _CalcAcceleration(Ride r) {
`_calculateAcceleration` RACZEJ
TROLLLLLLLL

2023-12-08 20:01 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metric.dart
> +  static List<double> _CalcAcceleration(Ride r) {
done

2023-12-08 20:04 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metric.dart
> +    for (int i = 0; i < r.engineSpeedList.length; i++) {
nie w przypadku, kiedy regularnie muszę dostać się do indeksu elementu 
unchanged

2023-12-08 20:07 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metric.dart
> +          overrunStartIdx = i;
done

2023-12-08 20:14 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metric.dart
> +              continue;
done

2023-12-08 20:16 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metric.dart
> +    }
done

2023-12-08 20:29 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metric.dart
> +      double acc = speed / MetricConstants.KMHtoMS / time.inSeconds;
wyjebałem przeliczanie na m/s i zmieniłem const wartość graniczną

2023-12-08 20:30 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metric.dart
> +      double acc = speed / MetricConstants.KMHtoMS / time.inSeconds;
done

2023-12-08 20:33 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metric.dart
> +      if (currDifference > minDifference) {
done

2023-12-08 20:35 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metric.dart
> +  static int _FindClosestGpsSample(Ride ride, DateTime sample, int lastGpsIndex) {
done

2023-12-08 20:35 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metric.dart
> +          overrun.GPSendIdx = lastGpsIndex;
done

2023-12-08 20:38 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metric.dart
> +  static int _FindClosestGpsSample(Ride ride, DateTime sample, int lastGpsIndex) {
#18

2023-12-08 20:59 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metric.dart
> +        overrunEndIdx = i - 1;
done

2023-12-09 02:55 UTC, Sosssen commented on lib/classes/overrun.dart
> +enum OverrunType { Undefined, TooHighRPM, TooFastAcceleration }
`tooHighRpm`

2023-12-09 03:15 UTC, Sosssen requested changes
KOŃCÓWKA

2023-12-09 03:15 UTC, Sosssen commented on lib/singletons/metrics.dart
> +    }
DO REFACTORu
załóż issue - idx1 ma szukać lewego punktu gps, idx2 ma szukać prawego punktu gps - wtedy zawsze mamy PROSTĄ

2023-12-09 03:15 UTC, Sosssen commented on lib/singletons/metrics.dart
> +      return List.empty();
`List<Overrun>.empty()` - readability

2023-12-09 03:15 UTC, Sosssen commented on lib/singletons/metrics.dart
> +      if (r.engineSpeedList[i] < MetricsConstants.maxRev) continue;
nie lubię jednolinijkowego `continue`, zwłaszcza że niżej w tej funkcji robisz w klamrach, jak już uparty będziesz na to, to chociaż STICK TO ONE CONVENTION

2023-12-09 03:15 UTC, Sosssen commented on lib/singletons/metrics.dart
> +    Duration minDifference = ride.positionList[closestGpsIndex].timestamp!.difference(sample).abs();
teoretycznie jak pusty to jebnie error
ale so far wywołujesz to w metrykach, jak w każdej sprawdzisz czy nie pusta, TO GI

2023-12-09 03:15 UTC, Sosssen commented on lib/singletons/metrics.dart
> +      if (r.engineSpeedList[i] < MetricsConstants.maxRev) continue;
teraz widzę, że wszędzie poza tym masz w klamrach, mniej zmieniania jak i tu dodasz klamry c; C:

2023-12-09 03:18 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metrics.dart
> +    }
#19

2023-12-09 03:18 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metrics.dart
> +      return List.empty();
done

2023-12-09 03:19 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metrics.dart
> +      if (r.engineSpeedList[i] < MetricsConstants.maxRev) continue;
done

2023-12-09 03:19 UTC, H3w9VH3F4L4Tq5MbsfRi commented on lib/singletons/metrics.dart
> +    Duration minDifference = ride.positionList[closestGpsIndex].timestamp!.difference(sample).abs();
unchanged

2023-12-09 03:30 UTC, Sosssen approved these changes
JEZU JAK SIĘ CIESZĘ

2023-12-09 03:31 UTC, merged